name: Predict house price!

on:
  push:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install pandas scikit-learn openpyxl

      - name: Run script and save output
        run: |
          python "ML gia nha.py" > ket_qua.txt
          echo "" >> ket_qua.txt

      - name: Upload result as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ket-qua
          path: ket_qua.txt
